<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dotnet_Project.Common\Dotnet_Project.Common.csproj" />
    <ProjectReference Include="..\Dotnet_Project.Service\Dotnet_Project.Service.csproj" />
    <ProjectReference Include="..\Dotnet_Project.Share\Dotnet_Project.Store.csproj" />
  </ItemGroup>

</Project>
